info:
  app:
    name: Fuel Log
    description: Fuel Log Application

# Actuator Endpoints Settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8090
  http2: # Enable HTTP/2 support
    enabled: true
  compression: # Server compression
    enabled: true
    min-response-size: 2048
    mime-types: application/json

# Data Source
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  datasource:
    driver: org.postgresql.postgresql
    url: jdbc:postgresql://localhost:5432/test-pg
    username: test-pg
    password: pswd_test
    initialization-mode: always
  data:
    mongodb:
      database: fuellogdb
      host: localhost
      port: 27017
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
